# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proof_pb2 as proof__pb2


class ChaumPedersenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parameters = channel.unary_unary(
                '/ChaumPedersenService/Parameters',
                request_serializer=proof__pb2.ParametersRequest.SerializeToString,
                response_deserializer=proof__pb2.ParametersResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/ChaumPedersenService/Register',
                request_serializer=proof__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=proof__pb2.RegistrationResponse.FromString,
                )
        self.CommitmentChallenge = channel.unary_unary(
                '/ChaumPedersenService/CommitmentChallenge',
                request_serializer=proof__pb2.CommitmentChallengeRequest.SerializeToString,
                response_deserializer=proof__pb2.CommitmentChallengeResponse.FromString,
                )
        self.VerifyProof = channel.unary_unary(
                '/ChaumPedersenService/VerifyProof',
                request_serializer=proof__pb2.VerifyProofRequest.SerializeToString,
                response_deserializer=proof__pb2.VerifyProofResponse.FromString,
                )


class ChaumPedersenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Parameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitmentChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChaumPedersenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parameters': grpc.unary_unary_rpc_method_handler(
                    servicer.Parameters,
                    request_deserializer=proof__pb2.ParametersRequest.FromString,
                    response_serializer=proof__pb2.ParametersResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proof__pb2.RegistrationRequest.FromString,
                    response_serializer=proof__pb2.RegistrationResponse.SerializeToString,
            ),
            'CommitmentChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitmentChallenge,
                    request_deserializer=proof__pb2.CommitmentChallengeRequest.FromString,
                    response_serializer=proof__pb2.CommitmentChallengeResponse.SerializeToString,
            ),
            'VerifyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyProof,
                    request_deserializer=proof__pb2.VerifyProofRequest.FromString,
                    response_serializer=proof__pb2.VerifyProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChaumPedersenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChaumPedersenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Parameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChaumPedersenService/Parameters',
            proof__pb2.ParametersRequest.SerializeToString,
            proof__pb2.ParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChaumPedersenService/Register',
            proof__pb2.RegistrationRequest.SerializeToString,
            proof__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitmentChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChaumPedersenService/CommitmentChallenge',
            proof__pb2.CommitmentChallengeRequest.SerializeToString,
            proof__pb2.CommitmentChallengeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChaumPedersenService/VerifyProof',
            proof__pb2.VerifyProofRequest.SerializeToString,
            proof__pb2.VerifyProofResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
