# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proof.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproof.proto\"\x13\n\x11ParametersRequest\"5\n\x12ParametersResponse\x12\t\n\x01g\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\x12\t\n\x01q\x18\x03 \x01(\x05\"-\n\x13RegistrationRequest\x12\n\n\x02y1\x18\x01 \x01(\x05\x12\n\n\x02y2\x18\x02 \x01(\x05\"\'\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n\x1a\x43ommitmentChallengeRequest\x12\n\n\x02r1\x18\x01 \x01(\x05\x12\n\n\x02r2\x18\x02 \x01(\x05\"(\n\x1b\x43ommitmentChallengeResponse\x12\t\n\x01\x63\x18\x01 \x01(\x05\"\x1f\n\x12VerifyProofRequest\x12\t\n\x01s\x18\x01 \x01(\x05\"7\n\x13VerifyProofResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x92\x02\n\x14\x43haumPedersenService\x12\x35\n\nParameters\x12\x12.ParametersRequest\x1a\x13.ParametersResponse\x12\x37\n\x08Register\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\x12P\n\x13\x43ommitmentChallenge\x12\x1b.CommitmentChallengeRequest\x1a\x1c.CommitmentChallengeResponse\x12\x38\n\x0bVerifyProof\x12\x13.VerifyProofRequest\x1a\x14.VerifyProofResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proof_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PARAMETERSREQUEST']._serialized_start=15
  _globals['_PARAMETERSREQUEST']._serialized_end=34
  _globals['_PARAMETERSRESPONSE']._serialized_start=36
  _globals['_PARAMETERSRESPONSE']._serialized_end=89
  _globals['_REGISTRATIONREQUEST']._serialized_start=91
  _globals['_REGISTRATIONREQUEST']._serialized_end=136
  _globals['_REGISTRATIONRESPONSE']._serialized_start=138
  _globals['_REGISTRATIONRESPONSE']._serialized_end=177
  _globals['_COMMITMENTCHALLENGEREQUEST']._serialized_start=179
  _globals['_COMMITMENTCHALLENGEREQUEST']._serialized_end=231
  _globals['_COMMITMENTCHALLENGERESPONSE']._serialized_start=233
  _globals['_COMMITMENTCHALLENGERESPONSE']._serialized_end=273
  _globals['_VERIFYPROOFREQUEST']._serialized_start=275
  _globals['_VERIFYPROOFREQUEST']._serialized_end=306
  _globals['_VERIFYPROOFRESPONSE']._serialized_start=308
  _globals['_VERIFYPROOFRESPONSE']._serialized_end=363
  _globals['_CHAUMPEDERSENSERVICE']._serialized_start=366
  _globals['_CHAUMPEDERSENSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
